<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../src/AccountApiClient.cs" Link="AccountApiClient.cs" />
    <Compile Include="../src/AccountTokenStore.cs" Link="AccountTokenStore.cs" />
  </ItemGroup>
</Project>
