using AmdNrAssistant;
using System.Text.Json;

var root = Path.Combine(Path.GetTempPath(), "amd-management-tests-" + Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
GameManagement.StorageOverride = Path.Combine(root, "records");
var count = 0;
void Assert(bool ok, string name) { if (!ok) throw new Exception(name); count++; Console.WriteLine("PASS " + name); }
void Reject(Action act, string name) { try { act(); } catch (IOException) { Assert(true, name); return; } throw new Exception("Expected rejection: " + name); }
string Game(string name) { var d = Path.Combine(root, name); Directory.CreateDirectory(d); var e = Path.Combine(d, name + ".exe"); File.WriteAllText(e, "fixture"); return e; }
var a = Game("a" + Guid.NewGuid().ToString("N")); var b = Game("b" + Guid.NewGuid().ToString("N")); var dir = Path.GetDirectoryName(a)!;
var proxy = Path.Combine(dir, "version.dll"); File.WriteAllText(proxy, "original");
GameManagement.Begin(a, 0); File.WriteAllText(proxy, "installed"); File.WriteAllText(Path.Combine(dir, "dlssnr_on_amd.ini"), "new"); GameManagement.Finish(a, true);
Assert(GameManagement.Read(a)?.Mode == 0 && GameManagement.Read(a)?.Phase == "installed", "persistent record");
Assert(GameManagement.Read(b) == null, "per-game isolation");
File.WriteAllText(proxy, "external edit"); Reject(() => GameManagement.Restore(a), "modified target blocks complete restore");
Assert(File.Exists(Path.Combine(dir, "dlssnr_on_amd.ini")), "preflight prevents partial removal");
File.WriteAllText(proxy, "installed"); var backup = Path.Combine(GameManagement.State(a), "version.dll.backup"); File.WriteAllText(backup, "corrupt");
Reject(() => GameManagement.Restore(a), "corrupt backup rejected"); Assert(File.ReadAllText(proxy) == "installed", "corrupt backup never copied");
File.WriteAllText(backup, "original"); GameManagement.Restore(a);
Assert(File.ReadAllText(proxy) == "original" && !File.Exists(Path.Combine(dir, "dlssnr_on_amd.ini")), "restore originals and remove additions");
GameManagement.Restore(a); Assert(GameManagement.Read(a)?.Phase == "restored", "idempotent restore");
GameManagement.Begin(b, 1); Reject(() => GameManagement.Restore(b), "interrupted external install fails closed");
var record = GameManagement.Read(a)!;
File.WriteAllText(Path.Combine(GameManagement.State(a), "record.json"), JsonSerializer.Serialize(record with { Files = new() { new("../outside.dll", "", "") } }));
Reject(() => GameManagement.Restore(a), "manifest traversal rejected");
Console.WriteLine($"{count} assertions passed. Fixtures retained at {root}");
Assert(!GameManagement.HasCompletedFrames("frame 0 processed (0 skipped)"), "zero frames not success");
Assert(!GameManagement.HasCompletedFrames("network job 10ms; Enabled=1"), "timing or enabled flag not success");
Assert(GameManagement.HasCompletedFrames("frame 240 processed (2 skipped)"), "documented add-on completed frame format");
var c = Game("legacy" + Guid.NewGuid().ToString("N")); var cd = Path.GetDirectoryName(c)!;
File.WriteAllText(Path.Combine(cd, "winmm.dll"), "unknown plugin");
File.WriteAllText(Path.Combine(cd, "nvngx_dlss.dll"), "native game DLSS");
File.WriteAllText(Path.Combine(cd, "d3d12.dll"), "game component");
var snapshot = GameManagement.LegacyCandidates(c);
Assert(snapshot.Count == 1 && snapshot.ContainsKey("winmm.dll"), "legacy cleanup excludes native DLSS and D3D12");
var wrong = new Dictionary<string,string>(snapshot) { ["../outside.dll"] = "bad" };
Reject(() => GameManagement.QuarantineLegacy(c, wrong), "unapproved path rejected");
File.WriteAllText(Path.Combine(cd, "winmm.dll"), "changed");
Reject(() => GameManagement.QuarantineLegacy(c, snapshot), "changed legacy snapshot blocks cleanup");
Assert(File.Exists(Path.Combine(cd, "winmm.dll")), "failed legacy preflight leaves files intact");
var archive = GameManagement.QuarantineLegacy(c, GameManagement.LegacyCandidates(c));
Assert(!File.Exists(Path.Combine(cd, "winmm.dll")) && File.ReadAllText(Path.Combine(archive, "winmm.dll")) == "changed", "unknown proxy recoverably quarantined");
Assert(File.Exists(Path.Combine(cd, "nvngx_dlss.dll")) && File.Exists(Path.Combine(archive, "manifest.json")), "native game file and recovery manifest preserved");
var d = Game("settings" + Guid.NewGuid().ToString("N")); var ini = Path.Combine(Path.GetDirectoryName(d)!, "dlssnr_on_amd.ini");
GameManagement.Begin(d, 0); File.WriteAllText(ini, "installed"); GameManagement.Finish(d, true);
File.WriteAllText(ini, "user changed settings");
GameManagement.Restore(d, true);
Assert(!File.Exists(ini) && Directory.EnumerateFiles(GameManagement.State(d), "*.ini", SearchOption.AllDirectories).Any(p => File.ReadAllText(p) == "user changed settings"), "edited settings archived then removed");
GameManagement.Restore(d, true); Assert(GameManagement.Read(d)?.Phase == "restored", "edited settings restore is repeatable");
Console.WriteLine($"Final: {count} assertions passed.");
