// Factual paraphrases reviewed against the pinned wiki snapshot, not MU test results.
export const reviewedCommit = '67f573d5acd9a719cc799159c798fb978b702446';
export const reviewedNotes = {
  'Cyberpunk 2077': [
    'AMD/Intel 开启路径追踪时，DLSS 输入会触发 DLSS RR 并出现噪点；上游建议改用 FSR 或 XeSS 输入。',
    '上游不建议使用 FSR 帧生成输入。界面出现 FSR4 输入选项，不代表本机显卡支持 FSR4 输出。',
    '上游记载 AMD 驱动 26.3.1 已修复此前 RT 反射/路径追踪崩溃问题。'
  ],
  'Black Myth: Wukong': [
    '显卡伪装可能造成蓝色纹理异常；上游建议 OptiPatcher，或设置 Dxgi=false。',
    '分辨率比例覆盖无效，重启会回到附近预设；FSR4 输入不受此项影响。',
    '原生 FSR 帧生成在 OptiScaler 启用后可能不流畅。',
    '游戏的 FSR3.1 DLL 用于 FSR4 升级；不支持 FSR4 的显卡不能据此使用 FSR3.1 输入。XeSS 输入只能转为 XeSS 或 FSR4 输出。'
  ],
  'Grand Theft Auto V Enhanced': [
    '需要关闭 BattlEye 才能加载 OptiScaler；不要将此离线路径用于受反作弊保护的联机游戏。',
    '超分辨率预设比例固定，覆盖设置不起作用。近期更新可能影响 INI 保存，来源提供 DirectStorageFix 方案。'
  ],
  'Wolfenstein: Youngblood': ['上游记录 Linux 可用；Windows 下 AMD/Intel 无法暴露 DLSS 与光追选项，因此不兼容。不能把 Linux 结果套用到 Windows。'],
  'Minecraft RTX': ['上游记录 Windows 可用；Linux/Wine 缺少该 UWP 游戏所需支持。'],
  'Atlas Fallen: Reign Of Sand': ['OptiScaler 无法接管该游戏在 DX12 或 Vulkan 下的 FSR2 输入。'],
  'EA Sports WRC': ['EA 反作弊阻止未知 DLL，所列 OptiScaler 接入路径不兼容。'],
  'Gears of War: Reloaded': ['存在 EAC 限制；虽然游戏有 FSR3.1 功能，但没有可供接入的独立 FSR DLL。'],
  '1666: Amsterdam': ['通过 DLSS 或 XeSS 输入使用 FSR4 时，需启用 Non-Linear Color Space，避免黑屏和闪烁。'],
  '7 Days To Die': ['上游接入条件是关闭 EAC；不要把这一配置用于受反作弊保护的联机游戏。'],
  'Ark: Survival Ascended': ['上游记录超分辨率可用，但帧生成不可用。'],
  'Ascend to ZERO': ['FSR 帧生成输出会导致启动崩溃。DLSS 输入使用 dxgi=true，FSR3.1 输入使用 dxgi=false。'],
  "Assassin's Creed Black Flag Resynced": ['上游建议关闭显卡伪装。'],
  'Assassin’s Creed Mirage': ['上游建议关闭显卡伪装，使用 FSR/XeSS 输入和原生 XeFG；XeSS 文件需更新到 2.1 SDK。'],
  'Assassin’s Creed Shadows': ['需要关闭 Ubisoft overlay；HDR 会产生严重拖影，上游不建议开启。'],
  'Assetto Corsa Competizione': ['可用 -dx12 启动参数切换 DX12；上游也记录默认 DX11 模式可用。'],
  'Assetto Corsa EVO': ['使用 DLSS 输入输出 FSR4 时，需要开启 AutoExposure。'],
  'Assetto Corsa Rally': ['FSR3.1 输入需要来源详情中的 Engine.ini 配置，否则可能崩溃。'],
  'Atomic Heart': ['FSR2 输入需要 Fsr2Pattern=true；无法启用时需检查光追是否关闭。'],
  'Avatar: Frontiers of Pandora': ['显卡伪装会影响室内光追亮度，因此上游默认关闭伪装。'],
  'Avowed': ['FSR4 需要开启 AutoExposure，其他条件见上游详情。'],
  'Beast of Reincarnation': ['FSR3 输入不受支持，其他输入及条件见上游详情。'],
  'Borderlands 4': ['显卡伪装有较大性能开销；上游推荐 FSR 或 XeSS 输入，Reflex 无需伪装。'],
  'Breathedge 2': ['上游只确认 DLSS 输入可用。'],
  'Car Dealer Simulator': ['上游使用 -dx12 启动参数。'],
  'Clair Obscur: Expedition 33': ['Ultra Quality 预设会造成渲染异常；全屏模式可能缓解崩溃。FSR4 过场闪烁可尝试 Non-Linear/sRGB。'],
  'Conan Exiles Enhanced': ['需在启动器中关闭 BattlEye，或按来源直接运行游戏程序；这不是受反作弊保护的联机支持声明。'],
  'Corsair Cove': ['Xbox Game Pass 版本使用 winmm.dll 文件名接入。'],
  'DEAD OR ALIVE 6 Last Round': ['OptiScaler 文件名需要 d3d12.dll 或 version.dll。'],
  'DEATH STRANDING 2: ON THE BEACH': ['DLSS 输入会闪烁，上游建议改用 XeSS 输入。'],
  'Destroy All Humans! 2 – Reprobed': ['上游要求使用 DX12。'],
  'Diablo IV': ['上游使用 DX12；项目整体不建议在受反作弊保护的在线游戏中注入。'],
  'Dinoblade': ['DLSS 输入不可用；DLSSG 输入需要上游 Unreal Engine Tweaks 配置。'],
  'Dragon Age: The Veilguard': ['FSR2 会出现画面异常；Linux 接入使用 winmm.dll。'],
  'Eastern Era': ['FSR 输入需要 Unreal Engine Tweaks 的 Engine.ini 修复；配置文件需按来源路径创建并设为只读。'],
  'Enshrouded': ['FSR2/FSR3 下草地和雾可能闪烁。'],
  'F1 25': ['上游明确仅限离线使用；DLSS 显卡伪装不可用，应设置 Dxgi=false。'],
  'Farming Simulator 25': ['使用 RTSS overlay 时需启用 Detours API Hooking。'],
  'FINAL FANTASY VII REBIRTH': ['AMD/Intel 建议使用 OptiPatcher，减少显卡伪装的性能开销与卡顿。'],
  'FINAL FANTASY XVI': ['FSR4 画质异常时可能需要启用 Non-Linear PQ Input。'],
  'Forspoken': ['需将 OptiScaler.dll 改名为 d3d12.dll，才能识别 DLSS 输入。'],
  'Forza Horizon 6': ['Game Pass/MS Store 版使用 d3d12.dll；overlay 可能需要 OverlayMenu=false，帧生成异常时可能需改回 auto。'],
  'Five Nights at Freddy’s: Security Breach': ['DLSS 默认开启，游戏设置没有关闭选项。'],
  'Frostpunk 2': ['FSR4 可使用 Non-Linear sRGB Input 改善画质；FSR 输入需应用上游崩溃修复，或用 Fsr3=false/Ffx=false 禁用。'],
  'Gothic 1 Remake': ['游戏会对超分辨率自动施加锐化，需要在游戏设置中适当降低。'],
  'Hell is Us': ['DLSS 输入输出 FSR4 的 Balanced 预设会闪烁，可更换预设或输入。'],
  'Hello Neighbor 2': ['游戏菜单没有显示 DLSS 选项，但上游记录 OptiScaler 可以接收到 DLSS 输入。'],
  'HITMAN World of Assassination': ['显卡伪装会禁用光追选项，AMD/Intel 建议使用 XeSS 输入。'],
  'Hogwarts Legacy': ['显卡伪装性能开销较大，上游建议使用 OptiPatcher。'],
  'House Flipper 2': ['可用 -force-d3d12 启动 DX12；上游也记录默认 DX11 可用。'],
  'Indiana Jones and the Great Circle': ['Linux 使用 FSR4 Vulkan/DX12 互操作需要 Proton 11。'],
  'Infinity Nikki': ['使用 version.dll 文件名；构建必须签名，否则会被反作弊阻止。'],
  'InZOI': ['OptiPatcher 可能需要允许未签名 Mod；帧生成建议使用 DLSSG 输入，菜单内帧生成不生效。'],
  'JDM: Japanese Drift Master': ['上游建议使用 DLSS 输入。'],
  'Jurassic World Evolution 3': ['伪装会引起植被渲染问题，上游建议使用 OptiPatcher。'],
  'Kena: Bridge of Spirits': ['OptiFG 可配合 HUDFix limit 1；非 NVIDIA 显卡需要 dxgi=auto 伪装。'],
  'Last Train Home': ['上游使用 -dx12 启动参数。'],
  'Mafia: The Old Country': ['DLSS 输入输出 FSR4 如有闪烁，可能需启用 Non-Linear Color/sRGB。'],
  'Manor Lords': ['输入预设倍率固定；DLSS 的部分预设和 XeSS 输入需要 Non-Linear sRGB，避免 FSR4 渲染异常。'],
  'MechWarrior 5: Mercenaries': ['上游使用 -dx12 启动参数。'],
  'METAL EDEN': ['FSR3.1 输入需要上游指定的 Engine.ini 崩溃修复。'],
  'Microsoft Flight Simulator 2024': ['打开特定窗口时崩溃，可按来源尝试 OverlayMenu=false。'],
  'Monster Hunter Wilds': ['需要 REFramework；OptiScaler.ini 设置 Dxgi=false 以避免崩溃。'],
  'Morbid Metal': ['首次选择 DLSS 后可能需要重启游戏。'],
  'MOUSE: P.I. For Hire': ['上游记录 Dxgi=false 时可显示 DLSS 输入。'],
  'Need For Speed Unbound': ['Linux 下 DLL 文件名使用 d3d12.dll。'],
  'NINJA GAIDEN 2 Black': ['Game Pass 版文件应放在 NINJAGAIDEN2BLACK.exe 旁；FSR4 过场闪烁可用 Non-Linear sRGB Input 缓解。'],
  'Nioh 3': ['DLSS 输入会退回 FSR 并可能启动崩溃，上游建议 XeSS 输入。'],
  'Onimusha: Way of the Sword': ['需要 REFramework，并按上游详情配置；SL Spoof 用于暴露 DLSS/DLSSG 输入。'],
  'Palworld': ['需要强制 DX12 以避免抖动；Linux 非 DX12 路径可能在开场崩溃。'],
  'PAYDAY 3': ['FSR3 输入默认会崩溃，需要上游详情中的修复。'],
  'Planet Coaster 2': ['FSR3 输入不可用，上游使用 DLSS 输入。'],
  'PRAGMATA': ['需要 REFramework，并按上游详情配置；SL Spoof 用于暴露 DLSS/DLSSG 输入。'],
  'Quarantine Zone: The Last Check': ['FSR4 的雨天等天空效果需要 Non-Linear Color Space 修复。'],
  'Ready or Not': ['输入分辨率通过游戏内分辨率比例滑块调整。'],
  'Red Dead Redemption 2': ['上游建议关闭 NV Reflex 以减少卡顿；Linux 路径使用 Proton、更新的 vkd3d-proton 和游戏内 DX12。'],
  'Rise of the Ronin': ['上游使用 Nukem 模块才能打开 OptiScaler 菜单。'],
  'Satisfactory': ['使用 DX12；接入目录是 Engine/Binaries/Win64，不能误放到 FactoryGame/Binaries/Win64。'],
  'Scorn': ['表内补充的 FSR4 加帧生成记录来自 Linux/RDNA3，不能直接视为 Windows 全显卡结论。'],
  'SILENT HILL: Townfall': ['上游建议关闭 Letterboxing 和 Mouse Smoothing。'],
  'Sons of the Forest': ['打开或关闭背包时可能出现异常。'],
  'Soulmask': ['需要先在 GameUserSettings.ini 中开启 DLSS，具体键值见来源。'],
  'Space Engineers 2': ['上游使用 dxgi.dll 文件名接入。'],
  'STAR WARS Jedi: Survivor': ['使用 Fullscreen Windowed；DLSS 开关可能需要重启游戏后才生效。'],
  'STAR WARS Zero Company': ['帧生成与低延迟选项受到 GPU 厂商限制。'],
  'Storage Hunter Simulator': ['FSR3.1 输入需要 Unreal Engine Tweaks，Engine.ini 需创建并设为只读，否则可能崩溃。'],
  'Tainted Grail: The Fall of Avalon': ['建议 -force-d3d12；FSR4 天空异常时可尝试 Non-Linear PQ Input。'],
  'TEKKEN 8': ['部分角色毛发质量异常；特定场景第二层在 FSR4 下有严重画面错误。'],
  'Tempest Rising': ['FSR4 闪屏时需要 Non-Linear sRGB Input。'],
  'The Alters': ['游戏内 FSR3 输入不能被识别，上游记录 DLSS 输入可用。'],
  'The Elder Scrolls IV: Oblivion Remastered': ['FSR3.1 输入如崩溃，可能需要 StreamlineSpoofing=false。'],
  'The Other Side': ['使用 -dx12；DLSSG 输入还需要上游 Unreal Engine Tweaks。'],
  'The RPG': ['此项为 Unity DX11；游戏菜单不能分别选择输入技术，实际输入取决于 GPU 厂商。'],
  'The Seven Deadly Sins: Origin': ['上游记录无法强制 DX12。'],
  'Titan Quest II': ['上游通过 Nukem 模块启用 FSR 帧生成。'],
  'Trepang2': ['建议 -dx12；游戏启动后可能重置为 Performance 预设，需要重新切换预设。'],
  'Until Dawn': ['FSR4 部分场景闪烁，需要 Non-Linear sRGB Input。'],
  'VEIN': ['DLSS 输入需要游戏目录中的 nvngx_dlss.dll；游戏占用 Insert 键，可设置 ShortcutKey=0x24。'],
  'Visions of Mana': ['需要启用 FSR2 pattern matching，或设置 Fsr2Pattern=true。'],
  'Warhammer 40,000: Space Marine 2': ['需要关闭 EAC 才能加载；这不代表受反作弊保护的联机支持。'],
  'Way of the Hunter': ['DX12 可使用 FSR2 输入；DX11 下 FSR2 输入会崩溃，需禁用并按来源使用替代路径。'],
  'Where Winds Meet': ['上游标注在线游戏使用风险，接入文件名为 dxgi.dll。'],
  'Wuthering Waves': ['上游标注在线游戏使用风险；新版本可使用 dxgi.dll 或 winmm.dll，并从指定游戏程序启动。'],
  'Yet Another Zombie Survivors': ['无需显卡伪装，应使用 Dxgi=false；可以强制 DX12。游戏显示的 FSR3.1 开关实际上仍是 DLSS 输入。'],
  'Yooka-Replaylee': ['Unity 版本的 FSR2 输入不受支持。'],
  'Zenless Zone Zero': ['上游标注在线游戏使用风险，必须查看具体接入条件。'],
  'Elden Ring': ['需要先安装 ERSS-FG Mod，才能提供超分辨率和帧生成输入；不是游戏原生支持声明。'],
  'FINAL FANTASY VII REMAKE INTERGRADE': ['需要 FF7 Remake Luma Mod，并使用 -dx11 启动。'],
  'Devil May Cry 5': ['需要 REFramework 的 PDUpscaler 分支及 PDPerfPlugin，具体加载顺序见来源。'],
  'Resident Evil 8 Village': ['需要 REFramework/PDUpscaler Mod；Windows 下 FSR4 输出会黑屏，其他超分辨率后端可能可用。'],
  'Darksiders III': ['Luma 路径要求游戏内抗锯齿设为 Epic。'],
  'GUILTY GEAR -STRIVE-': ['需要 Luma、Temporal Anti Aliasing 和额外 Engine.ini 配置；角色选择画面抗锯齿不生效。'],
  'OCTOPATH TRAVELER': ['Luma 路径需要额外 Engine.ini 配置，位置与键值见来源。'],
  'Remnant: From the Ashes': ['Luma 路径需要额外 Engine.ini 配置。'],
  'Roboquest': ['Luma 路径需要游戏内 TAA，Quality 设置为 3。'],
  'Spyro Reignited Trilogy': ['Luma 路径需要游戏内 High TAA。']
};
