<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AMD-DLSS-MU</AssemblyName>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup Condition="Exists('..\assets\nvngx_dlssnr.dll')">
    <EmbeddedResource Include="..\assets\nvngx_dlssnr.dll" LogicalName="AmdNrAssistant.nvngx_dlssnr.dll" />
  </ItemGroup>
  <ItemGroup Condition="Exists('..\assets\amd_dlss_mu_logo.png')">
    <EmbeddedResource Include="..\assets\amd_dlss_mu_logo.png" LogicalName="AmdNrAssistant.amd_dlss_mu_logo.png" />
  </ItemGroup>
</Project>
